import Foundation
import Testing

@testable import PattadarKit

/// The Swift land rules must agree with the TypeScript ones, case for case.
///
/// `packages/core` is the single definition of what an extent means and whether
/// a pin is plausible, and three web/RN heads import it directly. Swift cannot,
/// so the rules exist twice — and two implementations of land arithmetic drift
/// unless something forces them not to. This is that thing.
///
/// The vectors are generated by `bun run scripts/emit-vectors.ts` and are read
/// here through a symlink, so there is exactly one copy. Change a rule in
/// TypeScript without porting it and these tests fail.
private func loadVectors<T: Decodable>(_ name: String, as: T.Type) throws -> T {
    guard let url = Bundle.module.url(forResource: "Vectors/\(name)", withExtension: "json") else {
        // A missing vector file must fail loudly. Skipping would turn the whole
        // anti-drift mechanism into a no-op that still reports success.
        throw VectorError.missing(name)
    }
    return try JSONDecoder().decode(T.self, from: Data(contentsOf: url))
}

enum VectorError: Error, CustomStringConvertible {
    case missing(String)
    var description: String {
        switch self {
        case .missing(let n):
            "vectors/\(n).json not found — run `bun run scripts/emit-vectors.ts`"
        }
    }
}

// MARK: - Units

struct UnitVector: Decodable {
    let value: Double
    let label: String
    let key: String
    let acres: Double
}

@Test("Unit labels resolve the same way as packages/core")
func unitLabelsMatch() throws {
    let vectors = try loadVectors("units", as: [UnitVector].self)
    #expect(!vectors.isEmpty)
    for v in vectors {
        #expect(
            unitKey(v.label).rawValue == v.key,
            "label \"\(v.label)\" resolved to \(unitKey(v.label).rawValue), TypeScript says \(v.key)"
        )
    }
}

@Test("Extents convert to acres the same way as packages/core")
func unitConversionsMatch() throws {
    let vectors = try loadVectors("units", as: [UnitVector].self)
    for v in vectors {
        let got = toAcres(v.value, unitKey(v.label))
        #expect(
            abs(got - v.acres) < 1e-9,
            "\(v.value) \(v.label) -> \(got) acres, TypeScript says \(v.acres)"
        )
    }
}

@Test("A round trip through any unit is lossless")
func conversionRoundTrips() {
    for unit in UnitKey.allCases {
        let back = fromAcres(toAcres(123.456, unit), unit)
        #expect(abs(back - 123.456) < 1e-9, "\(unit.rawValue) round trip lost precision")
    }
}

// MARK: - Areas

struct AreaVector: Decodable {
    let text: String
    let sqyd: Double
}

@Test("Deed extents parse the same way as packages/core")
func areaParsingMatches() throws {
    let vectors = try loadVectors("areas", as: [AreaVector].self)
    #expect(!vectors.isEmpty)
    for v in vectors {
        let got = parseAreaSqYd(v.text)
        #expect(
            abs(got - v.sqyd) < 1e-9,
            "\"\(v.text)\" -> \(got), TypeScript says \(v.sqyd)"
        )
    }
}

@Test("A mixed fraction is never read as concatenated digits")
func mixedFractionIsNotConcatenated() {
    // The exact string from a real Guntur deed. Stripping non-digits gave
    // 41812 sq yd — a hundred times the truth — in both the app and the API.
    #expect(parseAreaSqYd("418-1/2 sq. yards") == 418.5)
}

// MARK: - Geo

struct GeoVector: Decodable {
    let name: String
    let a: LatLng
    let b: LatLng
    let km: Double
    let suspect: Bool
}

@Test("Distances and plausibility match packages/core")
func geoMatches() throws {
    let vectors = try loadVectors("geo", as: [GeoVector].self)
    #expect(!vectors.isEmpty)
    for v in vectors {
        let km = haversineKm(v.a, v.b)
        #expect(abs(km - v.km) < 0.01, "\(v.name): \(km) km, TypeScript says \(v.km)")
        let sanity = checkLocation(pin: v.a, centroid: v.b, placeName: "Katragunta")
        #expect(
            sanity.suspect == v.suspect,
            "\(v.name): suspect=\(sanity.suspect), TypeScript says \(v.suspect)"
        )
    }
}

@Test("An unverifiable pin is never reported as a wrong one")
func unknownCentroidIsNotSuspect() {
    let pin = LatLng(latitude: 37.37, longitude: -122.01)
    #expect(checkLocation(pin: pin, centroid: nil).suspect == false)
    #expect(checkLocation(pin: nil, centroid: pin).suspect == false)
}

// MARK: - The two area conventions

@Test("A property's area is in its own unit, a parcel's is acres")
func areaConventionsDiffer() {
    // The exact row from the database: 418.5 with unit "Sq.yd".
    #expect(propertyAreaText(landArea: 418.5, landUnit: "Sq.yd") == "418.5 Sq. yards")
    // 4840 sq yd to the acre.
    #expect(abs(propertyAcres(landArea: 4840, landUnit: "Sq.yd") - 1.0) < 1e-9)
    #expect(abs(propertyAcres(landArea: 418.5, landUnit: "Sq.yd") - 0.0864669) < 1e-6)
    // Reading it as acres — the bug — would have made it 418.5 acres.
    #expect(propertyAcres(landArea: 418.5, landUnit: "Sq.yd") < 1.0)
}

// MARK: - The unit must come from the document, not from an assumption

@Test("An extent carries the unit it was written in")
func extentUnitIsRead() {
    // The exact string from the ROR that was filed as 30 SQUARE YARDS.
    let ror = parseExtent("30.00 acres")
    #expect(ror.value == 30)
    #expect(ror.unit == .acre, "an ROR in acres must not be read as square yards")
    #expect(abs(toAcres(ror.value, ror.unit) - 30) < 1e-9)

    // Real deed strings from the Guntur documents.
    #expect(parseExtent("418-1/2 sq. yards").unit == .sqyd)
    #expect(parseExtent("418-1/2 sq. yards").value == 418.5)
    #expect(parseExtent("C.G.191 sq.yds (159.70 sq.mtrs)").unit == .sqyd)
    #expect(parseExtent("Cha.G 200 (sq. yards)").unit == .sqyd)
    #expect(parseExtent("2 hectares").unit == .hectare)
    #expect(parseExtent("40 guntas").unit == .gunta)
    #expect(abs(toAcres(parseExtent("40 guntas").value, parseExtent("40 guntas").unit) - 1) < 1e-9)
    // "Acres-Guntas" is decimal acres, and acre must win over gunta.
    #expect(parseExtent("2.5 Acres-Guntas").unit == .acre)
    #expect(parseExtent("1200 sq ft").unit == .sqft)

    // No unit written: the caller's default applies, not a silent guess.
    #expect(parseExtent("240", default: .sqyd).unit == .sqyd)
    #expect(parseExtent("240", default: .acre).unit == .acre)
}

// MARK: - Dates a person reads

@Test("An ISO date is written the way it is spoken")
func isoDatesAreHumanised() {
    #expect(humanDate("2003-01-04") == "4 January 2003")
    #expect(humanDate("2009-07-19") == "19 July 2009")
    #expect(humanDate("2024-12-31T10:04:00") == "31 December 2024")
}

@Test("An ambiguous date is never guessed at")
func ambiguousDatesAreLeftAlone() {
    // 4 January or 1 April? In a land record that is two different deeds, so
    // the raw text is the only honest answer.
    #expect(humanDate("04-01-2003") == "04-01-2003")
    // A day above 12 settles it.
    #expect(humanDate("19-07-2009") == "19 July 2009")
    #expect(humanDate("19/07/2009") == "19 July 2009")
    // Nonsense is passed through rather than turned into a plausible date.
    #expect(humanDate("2003-13-45") == "2003-13-45")
    #expect(humanDate("") == "")
    #expect(humanDate("Book 1, Vol 1488") == "Book 1, Vol 1488")
}

// MARK: - The geocoder ladder

struct PlaceVector: Decodable {
    let line: String
    let candidates: [String]
}

@Test("The geocoder ladder is climbed in the same order as packages/core")
func placeCandidatesMatch() throws {
    let vectors = try loadVectors("places", as: [PlaceVector].self)
    #expect(!vectors.isEmpty)
    for v in vectors {
        let got = placeCandidates(v.line)
        #expect(
            got == v.candidates,
            "\"\(v.line)\" -> \(got), TypeScript says \(v.candidates)"
        )
    }
}

@Test("A village filed under the wrong parent still gets a rung of its own")
func villageIsTriedAlone() {
    // OpenStreetMap files Konakanamitla under Markapuram, so the full chain
    // matches NOTHING. Without a village-alone rung the next try is the whole
    // district — a 20 km frame for a village that resolves on its own.
    let tries = placeCandidates("Konakanamitla, Prakasam")
    let village = tries.firstIndex(of: "Konakanamitla, Andhra Pradesh")
    let district = tries.firstIndex(of: "Prakasam, Andhra Pradesh")
    #expect(village != nil, "the village must be tried on its own")
    #expect(district != nil)
    #expect(village! < district!, "the village must be tried BEFORE the district")
}

// MARK: - Where the pin lands on a record that has a shape

struct RingVector: Decodable {
    let name: String
    let ring: [LatLng]
    let centroid: LatLng?
}

@Test("A boundary's pin lands where packages/core puts it")
func ringCentroidsMatch() throws {
    let vectors = try loadVectors("rings", as: [RingVector].self)
    #expect(!vectors.isEmpty)
    for v in vectors {
        let got = ringCentroid(v.ring)
        switch (got, v.centroid) {
        case (nil, nil):
            break
        case let (g?, c?):
            #expect(
                abs(g.latitude - c.latitude) < 1e-6 && abs(g.longitude - c.longitude) < 1e-6,
                "\(v.name): (\(g.latitude), \(g.longitude)), TypeScript says (\(c.latitude), \(c.longitude))"
            )
        default:
            Issue.record("\(v.name): one side returned nil and the other did not")
        }
    }
}

@Test("An L-shaped field is not pinned outside itself")
func lShapeIsWeightedByArea() throws {
    // Averaging the corners drags the pin towards whichever edge the surveyor
    // marked most often. On this L the plain average sits in the notch — off
    // the land — which is why the rule is area weighting, not averaging.
    let ring = [
        LatLng(latitude: 15.0, longitude: 79.0), LatLng(latitude: 15.0, longitude: 79.3),
        LatLng(latitude: 15.1, longitude: 79.3), LatLng(latitude: 15.1, longitude: 79.1),
        LatLng(latitude: 15.3, longitude: 79.1), LatLng(latitude: 15.3, longitude: 79.0),
    ]
    let plainLat = ring.map(\.latitude).reduce(0, +) / Double(ring.count)
    let plainLon = ring.map(\.longitude).reduce(0, +) / Double(ring.count)
    let got = try #require(ringCentroid(ring))
    #expect(abs(got.latitude - plainLat) > 1e-6 || abs(got.longitude - plainLon) > 1e-6)
}

// MARK: - Imported boundary files and fence plans
private struct BoundaryFileVector: Decodable {
    let text: String
    let fileName: String
    let ring: [[Double]]
    let format: String
    let name: String
}
@Test("Boundary imports agree with core, including the largest-area MultiPolygon")
func boundaryFileVectorsMatch() throws {
    let vectors = try loadVectors("boundaries", as: [BoundaryFileVector].self)
    #expect(!vectors.isEmpty)
    for v in vectors {
        let result = try parseBoundaryFile(v.text, fileName: v.fileName)
        #expect(result.format == v.format)
        #expect(result.name == v.name)
        #expect(result.ring == v.ring.map { LatLng(latitude: $0[0], longitude: $0[1]) })
        let exported = try toBoundaryGeoJson(result.ring)
        #expect(try parseBoundaryFile(exported).ring == result.ring)
    }
}
private struct FenceVector: Decodable {
    let sideMetres: [Double]
    let opts: FenceOptions
    let expected: FencePlan
}
@Test("Fencing counts shared corner posts and matches every core estimate")
func fenceVectorsMatch() throws {
    let vectors = try loadVectors("fences", as: [FenceVector].self)
    #expect(!vectors.isEmpty)
    for v in vectors {
        let got = fencePlan(v.sideMetres, options: v.opts), expected = v.expected
        #expect(got.posts == expected.posts)
        #expect(got.sides == expected.sides)
        #expect(got.corners == expected.corners)
        #expect(got.cornerPosts == expected.cornerPosts)
        #expect(got.linePosts == expected.linePosts)
        #expect(abs(got.perimeter - expected.perimeter) < 1e-8)
        #expect(abs(got.wire - expected.wire) < 1e-8)
        #expect(abs(got.postCost - expected.postCost) < 1e-8)
        #expect(abs(got.wireCost - expected.wireCost) < 1e-8)
        #expect(abs(got.cost - expected.cost) < 1e-8)
        #expect(got.bySide == expected.bySide)
    }
}
