/**
 * The source of theme-init.js: the classic script each app loads in <head>,
 * before its own bundle, so the first frame is already in the saved scheme.
 *
 * Built from the registry and written by scripts/emit-theme-init.ts; never
 * edited by hand. scripts/palette-tests.ts fails when a committed copy differs
 * from what this returns, so the script cannot drift from the pack.
 *
 * What the script does, in order:
 *  1. Once (until the `migrated` marker is set): carry the app's older theme
 *     key into MUI's keys. The old key wins over anything MUI already holds,
 *     because that is the menu people actually used. It is left in place.
 *  2. Resolve the active scheme exactly as MUI's useCurrentColorScheme will:
 *     the stored mode ('system' follows the device), then that mode's stored
 *     scheme, each falling back to the registry's defaults. A value that is
 *     not a registered scheme is never written into the page.
 *  3. `?scheme=<id>` on the address opens that scheme as if it had been
 *     chosen from the menu — saved, so MUI agrees when it mounts — and is then
 *     taken off the address, so a reload or a later choice is never overruled
 *     by it. Only a registered id is honoured; anything else is ignored and
 *     the address is left alone. This is how a scheme is opened for review
 *     (design.md § Theme choice and persistence).
 *  4. Put the scheme on <html data-scheme> and paint each scheme's ground and
 *     color-scheme on <html>, so nothing flashes before MUI's own CSS lands.
 *
 * It reads and writes no key but the theme's, and nothing from the URL but
 * `scheme`.
 */
import { LEGACY_THEME_KEYS, THEME_STORAGE, themeDefaults, type ThemeApp } from './choice';
import { parseColour, toHex } from './contrast';
import { schemes } from './registry';

/** The `<html>` rules theme-init.js inserts: each scheme's ground and mode. */
export function themeInitCss(): string {
  return schemes
    .map((s) => `html[data-scheme="${s.id}"]{background-color:${toHex(parseColour(s.palette.ground))};color-scheme:${s.mode}}`)
    .join('');
}

export function themeInitSource(app: ThemeApp): string {
  const d = themeDefaults(app);
  const config = {
    schemes: Object.fromEntries(schemes.map((s) => [s.id, s.mode])),
    defaults: { mode: d.mode, light: d.light, dark: d.dark },
    keys: THEME_STORAGE,
    legacy: LEGACY_THEME_KEYS[app],
  };
  return `/* Generated by scripts/emit-theme-init.ts from packages/tokens/src/palette.
 * Do not edit by hand: change the registry, then run
 * \`bun run scripts/emit-theme-init.ts\`.
 *
 * Runs before the app's own bundle. It reads the saved colour scheme from
 * MUI's keys (carrying the older key into them once), honours ?scheme=<id>
 * for a registered scheme, puts it on <html data-scheme> and paints that
 * scheme's ground, so the first frame is already the right colour. It reads
 * and writes no key but the theme's, and nothing from the address but scheme.
 */
(function () {
  'use strict';
  var C = ${JSON.stringify(config)};
  var CSS = ${JSON.stringify(themeInitCss())};
  var has = function (o, k) { return typeof k === 'string' && Object.prototype.hasOwnProperty.call(o, k); };
  var scheme = C.defaults[C.defaults.mode];
  try {
    var store = window.localStorage;
    if (!store.getItem(C.keys.migrated)) {
      for (var i = 0; i < C.legacy.length; i += 1) {
        var values = C.legacy[i].values;
        var was = store.getItem(C.legacy[i].key);
        if (has(values, was) && has(C.schemes, values[was])) {
          var id = values[was];
          store.setItem(C.keys.mode, C.schemes[id]);
          store.setItem(C.keys.scheme + '-' + C.schemes[id], id);
          break;
        }
      }
      store.setItem(C.keys.migrated, '1');
    }
    var mode = store.getItem(C.keys.mode) || C.defaults.mode;
    if (mode === 'system') {
      mode = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    }
    if (mode === 'light' || mode === 'dark') {
      var saved = store.getItem(C.keys.scheme + '-' + mode) || C.defaults[mode];
      scheme = has(C.schemes, saved) ? saved : C.defaults[mode];
    }
  } catch (e) {
    // Storage refused (blocked, or a private window): the default scheme.
  }
  try {
    var asked = new URLSearchParams(window.location.search).get('scheme');
    if (has(C.schemes, asked)) {
      scheme = asked;
      try {
        window.localStorage.setItem(C.keys.mode, C.schemes[asked]);
        window.localStorage.setItem(C.keys.scheme + '-' + C.schemes[asked], asked);
      } catch (e) {
        // Not saved: it shows on this page only.
      }
      var url = new URL(window.location.href);
      url.searchParams.delete('scheme');
      window.history.replaceState(window.history.state, '', url.pathname + url.search + url.hash);
    }
  } catch (e) {
    // No address to read: the saved scheme stands.
  }
  document.documentElement.setAttribute('data-scheme', scheme);
  var style = document.createElement('style');
  style.setAttribute('data-theme-init', '');
  style.textContent = CSS;
  document.head.appendChild(style);
})();
`;
}
