"""The LOCAL trust root: a laptop keypair standing in for the Cognito pool.

This is not an auth-disable knob — the gateway still has none. In local mode
the exact same validation pipeline runs (signature, issuer, expiry,
token_use, client_id allowlist, email claim; see cognito_jwt.verify_token);
the only thing that changes is WHOSE key it trusts: an RSA key generated by
scripts/start-local.sh instead of the pool's published JWKS. That keeps the
phone-local loop working with no internet at all — the hosted UI, the JWKS
fetch and token refresh are the three places real Cognito needs the network.

Two properties keep this out of production:
- Activation requires LOCAL_AUTH_KEY_FILE to name a readable private key at
  startup (main.py fails FAST on a set-but-unreadable path). The ECS image
  carries no key file and the task definitions never set the variable.
- A token minted here is rejected by any gateway trusting the real pool —
  the issuer string differs AND the signature does not verify against
  Cognito's JWKS. Trust only ever widens on the laptop, never toward prod:
  the LOCAL gateway additionally accepts real-pool tokens (main.py wires
  the pool as a second trust root, so a phone signed in through the real
  hosted UI works against this stack), but no production gateway ever
  accepts a laptop token.
"""

import hashlib
import time
from typing import Any, Dict, List, Optional

from cryptography.hazmat.primitives import serialization
from fastapi import APIRouter, HTTPException
from jose import jwk, jwt

# Deliberately not a URL: nothing should ever try to fetch JWKS for it.
ISSUER = "pattadar-local-auth"

# A working day. There is no refresh path — the dev door just re-mints.
TOKEN_TTL_SECONDS = 12 * 3600


class LocalTrust:
    """JWKS stand-in with JWKSCache's async surface, keys from a PEM file."""

    def __init__(self, key_file: str):
        with open(key_file, "rb") as f:
            pem = f.read()
        private = serialization.load_pem_private_key(pem, password=None)
        self._private_pem = pem.decode()
        public_der = private.public_key().public_bytes(
            serialization.Encoding.DER,
            serialization.PublicFormat.SubjectPublicKeyInfo,
        )
        public_pem = private.public_key().public_bytes(
            serialization.Encoding.PEM,
            serialization.PublicFormat.SubjectPublicKeyInfo,
        ).decode()
        # kid from the key material itself: a regenerated key is a new kid,
        # so a stale token can never match the fresh key by accident.
        self.kid = hashlib.sha256(public_der).hexdigest()[:16]
        key_dict = jwk.construct(public_pem, algorithm="RS256").to_dict()
        key_dict.update({"kid": self.kid, "use": "sig", "alg": "RS256"})
        self._jwk = key_dict

    async def get_key(
        self, kid: str, *, http_client: Optional[Any] = None
    ) -> Dict[str, Any]:
        if kid != self.kid:
            raise KeyError(f"Signing key '{kid}' not found in local trust")
        return self._jwk

    async def get_keys(self, *, http_client: Optional[Any] = None) -> List[Dict[str, Any]]:
        return [self._jwk]

    async def refresh(self, *, http_client: Optional[Any] = None) -> None:
        return None

    def mint(self, user: str, client_id: str) -> Dict[str, Any]:
        """Access + id token for a local user, shaped like Cognito's answer.

        The claims contract is the real one: token_use/client_id/email are
        exactly what verify_token demands, and the email is what the
        identity rule (auth._normalize_user_id) keys every record on — so
        "u01" lands on u01's seeded rows just like a real sign-in would.
        """
        email = user if "@" in user else f"{user}@local"
        email = email.strip().lower()
        now = int(time.time())
        base = {"iss": ISSUER, "sub": email, "email": email,
                "iat": now, "exp": now + TOKEN_TTL_SECONDS}
        access = jwt.encode(
            {**base, "token_use": "access", "client_id": client_id},
            self._private_pem, algorithm="RS256", headers={"kid": self.kid})
        id_token = jwt.encode(
            {**base, "token_use": "id", "aud": client_id},
            self._private_pem, algorithm="RS256", headers={"kid": self.kid})
        return {"access_token": access, "id_token": id_token,
                "expires_in": TOKEN_TTL_SECONDS, "token_type": "Bearer"}


router = APIRouter()


@router.post("/local-auth/token")
async def local_token(body: Dict[str, Any]):
    """Mint tokens for a local user. 404s unless the local trust root is
    active — on the real pool this route is indistinguishable from absent."""
    from . import auth  # runtime state, set by main.py's lifespan

    cfg = auth.jwt_config
    trust = auth.jwks_cache
    if not (isinstance(trust, LocalTrust) and cfg is not None and cfg.issuer == ISSUER):
        raise HTTPException(status_code=404, detail="Not Found")
    user = str((body or {}).get("user") or (body or {}).get("email") or "").strip()
    if not user:
        raise HTTPException(status_code=400, detail={"error": "user required"})
    client_ids = sorted(cfg.client_ids)
    if not client_ids:
        # Same fail-closed stance as validation: no allowlist, no tokens.
        raise HTTPException(status_code=500, detail={"error": "no app clients configured"})
    return trust.mint(user, client_ids[0])
