"""Transport-independent handlers for the Pattadar historical record corpus."""
from __future__ import annotations

import asyncio
import hashlib
import re
import time
from datetime import datetime, timezone
from typing import Any, Literal

from .database import ReadOnlyDatabase
from .embeddings import dependency_available, embed_query, to_vector_literal
from .exceptions import PublicRecordsUnavailable, ToolInputError
from .settings import PublicRecordSettings

Metric = Literal["count", "sum_market_value", "sum_consideration_value", "sum_extent"]
PUBLIC_RECORD_TOOL_NAMES = (
    "get_analytical_stats",
    "get_property_history",
    "search_semantic_boundaries",
    "get_record_by_rid",
    "resolve_village",
    "find_properties_by_party",
    "get_price_rates",
    "generate_report",
)

_AGGREGATES = {
    "count": "count(*)",
    "sum_market_value": "COALESCE(SUM(market_value), 0)",
    "sum_consideration_value": "COALESCE(SUM(consideration_value), 0)",
}
_MIN_PARTY_SIMILARITY = 0.5
_WS = re.compile(r"\s+")
_NAME_SEPARATORS = re.compile(r"[.,\s]+")
_RECORD_COLUMNS = (
    "rid, s_no, doc_no, year, sro_name, book_no, page_no, "
    "village, survey_no, plot_no, house_no, apartment_name, "
    "extent_val, extent_unit, property_type, land_class, "
    "transaction_type, txn_class, market_value, consideration_value, "
    "reg_date, exec_date, pres_date, sellers, buyers, other_parties, "
    "boundary_north, boundary_south, boundary_east, boundary_west, parse_status"
)
_HISTORY_COLUMNS = (
    "rid, s_no, reg_date, transaction_type, sellers, buyers, "
    "extent_val, extent_unit, market_value"
)
_BRAND = "CONFIDENTIAL — pattadar.com LLC"
_AI_DISCLAIMER = (
    "This report was generated by an AI system from a historical public-record reference "
    "corpus. It may contain errors or omissions and is provided without warranty. It is not "
    "proof of identity, ownership, current legal title, or a live government lookup. Verify "
    "against official IGRS records before any legal, financial, or transactional decision."
)


def _normalize_village(name: str) -> str:
    return _WS.sub(" ", name or "").strip().upper()


def _normalize_name(name: str | None) -> str:
    return _NAME_SEPARATORS.sub(" ", name or "").strip().upper()


def _inr(value: Any) -> str:
    if value is None:
        return "—"
    number = float(value)
    if number >= 1e7:
        return f"₹{number / 1e7:.2f} Cr"
    if number >= 1e5:
        return f"₹{number / 1e5:.2f} L"
    return f"₹{number:,.0f}"


def _num(value: Any) -> str:
    return "—" if value is None else f"{int(value):,}"


def _cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").replace("\r", " ")


def _table(headers: list[str], rows: list[list[Any]]) -> str:
    if not rows:
        return "_No data for this scope._\n"
    output = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    output.extend("| " + " | ".join(_cell(value) for value in row) + " |" for row in rows)
    return "\n".join(output) + "\n"


def _report_id(now: datetime, scope: str) -> str:
    digest = hashlib.sha256(scope.encode()).hexdigest()[:6].upper()
    return f"PTR-{now:%Y%m%d-%H%M%S}-{digest}"


def _header(
    heading: str,
    report_id: str,
    now: datetime,
    scope: str,
    coverage: str | None = None,
) -> list[str]:
    lines = [
        f"# {heading}",
        "",
        f"**Report ID:** `{report_id}`  |  **Generated:** {now:%Y-%m-%d %H:%M} UTC",
        f"**Scope:** {scope}",
    ]
    if coverage:
        lines.append(f"**Coverage:** {coverage}")
    lines.append("\n---\n")
    return lines


def _footer(report_id: str, now: datetime) -> list[str]:
    return [
        "\n---\n",
        f"**{_BRAND} · © {now:%Y} All rights reserved.**",
        "",
        f"> ⚠️ _{_AI_DISCLAIMER}_",
        "",
        f"<sub>{report_id} · pattadar.com · page 1 of 1</sub>",
    ]


class PublicRecordsService:
    """Read-only record operations shared by SDK tools and readiness checks."""

    def __init__(self, settings: PublicRecordSettings):
        self.settings = settings
        self.db = ReadOnlyDatabase(settings)
        self._capability_lock = asyncio.Lock()
        self._capability_checked_at = 0.0
        self._capability_cache = self._unavailable_capability()

    @staticmethod
    def _unavailable_capability() -> dict[str, Any]:
        return {
            "ready": False,
            "status": "temporarily_unavailable",
            "tool_count": len(PUBLIC_RECORD_TOOL_NAMES),
            "semantic_search_ready": False,
        }

    async def close(self) -> None:
        await self.db.close()

    async def capabilities(self, *, force: bool = False) -> dict[str, Any]:
        """Return a short-lived, redacted readiness summary."""
        async with self._capability_lock:
            if (
                self._capability_checked_at
                and not force
                and time.monotonic() - self._capability_checked_at < 30
            ):
                return dict(self._capability_cache)
            capability = self._unavailable_capability()
            if self.settings.configured:
                try:
                    tables = await self.db.inspect_schema()
                    ready = bool(tables.get("records") and tables.get("party"))
                    capability = {
                        "ready": ready,
                        "status": "ready" if ready else "temporarily_unavailable",
                        "tool_count": len(PUBLIC_RECORD_TOOL_NAMES),
                        "semantic_search_ready": bool(
                            ready
                            and tables.get("vectors")
                            and self.settings.embeddings_enabled
                            and dependency_available()
                        ),
                    }
                except PublicRecordsUnavailable:
                    pass
            self._capability_cache = capability
            self._capability_checked_at = time.monotonic()
            return dict(capability)

    async def resolve_village_norm(self, name: str, fuzzy: bool = True) -> str | None:
        table = self.settings.records_fqn
        normalized = _normalize_village(name)
        if not normalized:
            return None
        exact = await self.db.fetch_all(
            f"SELECT village_norm FROM {table} WHERE village_norm = %(v)s LIMIT 1",
            {"v": normalized},
        )
        if exact:
            return normalized
        if not fuzzy:
            return None
        rows = await self.db.fetch_all(
            f"SELECT village_norm, max(similarity(village_norm, %(n)s)) AS sim "
            f"FROM {table} WHERE village_norm %% %(n)s GROUP BY village_norm "
            "ORDER BY sim DESC LIMIT 1",
            {"n": normalized},
        )
        return rows[0]["village_norm"] if rows else None

    async def resolve_village(self, name: str, limit: int = 5) -> list[dict[str, Any]]:
        table = self.settings.records_fqn
        normalized = _normalize_village(name)
        if not normalized:
            return []
        return await self.db.fetch_all(
            f"SELECT village_norm, max(similarity(village_norm, %(n)s)) AS similarity, "
            f"count(*) AS record_count FROM {table} WHERE village_norm %% %(n)s "
            "GROUP BY village_norm ORDER BY similarity DESC LIMIT %(k)s",
            {"n": normalized, "k": max(1, min(int(limit), 50))},
        )

    async def get_analytical_stats(
        self,
        village: str,
        metric: Metric,
        year: int | None = None,
        transaction_type: str | None = None,
        transaction_class: str | None = None,
        land_class: str | None = None,
        sro: str | None = None,
        fuzzy_village: bool = True,
    ) -> dict[str, Any]:
        if metric not in (*_AGGREGATES, "sum_extent"):
            raise ToolInputError("Unsupported analytical metric.")
        resolved = await self.resolve_village_norm(village, fuzzy_village)
        filters = {
            "year": year,
            "transaction_type": transaction_type,
            "transaction_class": transaction_class,
            "land_class": land_class,
            "sro": sro,
        }
        if resolved is None:
            return {
                "resolved_village": None,
                "metric": metric,
                "value": 0,
                "row_count": 0,
                "filters": filters,
                "note": "village not found",
            }

        where = ["village_norm = %(v)s"]
        params: dict[str, Any] = {"v": resolved}
        if year is not None:
            where.append("year = %(y)s")
            params["y"] = year
        if transaction_type:
            where.append("transaction_type ILIKE %(transaction_type)s")
            params["transaction_type"] = f"%{transaction_type}%"
        if transaction_class:
            where.append("txn_class = %(transaction_class)s")
            params["transaction_class"] = transaction_class.upper()
        if land_class:
            where.append("land_class = %(land_class)s")
            params["land_class"] = land_class.upper()
        if sro:
            where.append("sro_name ILIKE %(sro)s")
            params["sro"] = f"%{sro}%"
        where_sql = " AND ".join(where)
        table = self.settings.records_fqn

        if metric == "sum_extent":
            rows = await self.db.fetch_all(
                f"SELECT extent_unit, COALESCE(SUM(extent_val), 0) AS s, count(*) AS c "
                f"FROM {table} WHERE {where_sql} GROUP BY extent_unit ORDER BY s DESC",
                params,
            )
            return {
                "resolved_village": resolved,
                "metric": metric,
                "value_by_unit": {str(row["extent_unit"] or "unknown"): row["s"] for row in rows},
                "row_count": sum(row["c"] for row in rows),
                "filters": filters,
            }

        rows = await self.db.fetch_all(
            f"SELECT {_AGGREGATES[metric]} AS value, count(*) AS row_count "
            f"FROM {table} WHERE {where_sql}",
            params,
        )
        row = rows[0]
        return {
            "resolved_village": resolved,
            "metric": metric,
            "value": row["value"] or 0,
            "row_count": row["row_count"],
            "filters": filters,
        }

    async def get_property_history(
        self,
        village: str | None = None,
        survey_no: str | None = None,
        plot_no: str | None = None,
        house_no: str | None = None,
        rid: str | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> dict[str, Any]:
        page_limit = max(1, min(int(limit), 200))
        page_offset = max(0, int(offset))
        if rid:
            where, params = "rid = %(rid)s", {"rid": rid}
        else:
            if not village or not (survey_no or plot_no or house_no):
                raise ToolInputError(
                    "Provide rid, or village plus one of survey_no/plot_no/house_no."
                )
            resolved = await self.resolve_village_norm(village, fuzzy=True)
            if resolved is None:
                return {
                    "records": [],
                    "pagination": {
                        "limit": page_limit,
                        "offset": page_offset,
                        "has_more": False,
                    },
                }
            clauses = ["village_norm = %(v)s"]
            params = {"v": resolved}
            if survey_no:
                clauses.append("survey_no ~ %(survey_no)s")
                params["survey_no"] = r"\m" + re.escape(survey_no.strip()) + r"\M"
            elif plot_no:
                clauses.append("plot_no = %(plot_no)s")
                params["plot_no"] = plot_no
            else:
                clauses.append("house_no = %(house_no)s")
                params["house_no"] = house_no
            where = " AND ".join(clauses)
        params.update({"page_size": page_limit + 1, "page_offset": page_offset})
        rows = await self.db.fetch_all(
            f"SELECT {_HISTORY_COLUMNS} FROM {self.settings.records_fqn} WHERE {where} "
            "ORDER BY reg_date ASC NULLS LAST, rid, s_no "
            "LIMIT %(page_size)s OFFSET %(page_offset)s",
            params,
        )
        has_more = len(rows) > page_limit
        return {
            "records": rows[:page_limit],
            "pagination": {
                "limit": page_limit,
                "offset": page_offset,
                "has_more": has_more,
                "next_offset": page_offset + page_limit if has_more else None,
            },
        }

    async def get_record_by_rid(
        self, rid: str, s_no: int | None = None
    ) -> list[dict[str, Any]]:
        if not rid.strip():
            raise ToolInputError("rid is required.")
        where = "rid = %(rid)s"
        params: dict[str, Any] = {"rid": rid}
        if s_no is not None:
            where += " AND s_no = %(s_no)s"
            params["s_no"] = s_no
            params["record_limit"] = 2
        else:
            params["record_limit"] = 201
        rows = await self.db.fetch_all(
            f"SELECT {_RECORD_COLUMNS} FROM {self.settings.records_fqn} "
            f"WHERE {where} ORDER BY s_no LIMIT %(record_limit)s",
            params,
        )
        if s_no is not None and len(rows) > 1:
            raise ToolInputError(
                "The corpus contains duplicate rows for this (rid, s_no) identity."
            )
        if s_no is None and len(rows) > 200:
            raise ToolInputError(
                "This document has more than 200 property rows; provide s_no for an exact record."
            )
        return rows

    async def find_properties_by_party(
        self,
        name: str,
        side: str | None = None,
        limit: int = 20,
        min_similarity: float = 0.6,
    ) -> list[dict[str, Any]]:
        query = _normalize_name(name)
        if not query:
            return []
        threshold = min(1.0, max(_MIN_PARTY_SIMILARITY, float(min_similarity)))
        where = "p.name_norm %% %(query)s"
        params: dict[str, Any] = {"query": query, "limit": max(1, min(int(limit), 100))}
        if side:
            normalized_side = side.strip().lower()
            if normalized_side not in {"executant", "claimant"}:
                raise ToolInputError("side must be executant or claimant.")
            where += " AND p.side = %(side)s"
            params["side"] = normalized_side
        sql = (
            "SELECT p.rid, p.s_no, p.name AS matched_name, p.role, p.side, "
            "similarity(p.name_norm, %(query)s) AS score, "
            "r.village, r.survey_no, r.transaction_type, r.reg_date, "
            "r.extent_val, r.extent_unit "
            f"FROM {self.settings.party_fqn} p "
            f"JOIN {self.settings.records_fqn} r USING (rid, s_no) "
            f"WHERE {where} ORDER BY score DESC, r.reg_date DESC NULLS LAST LIMIT %(limit)s"
        )
        return await self.db.fetch_all(
            sql,
            params,
            local_settings={"pg_trgm.similarity_threshold": threshold},
        )

    async def get_price_rates(
        self,
        village: str,
        land_class: str | None = None,
        transaction_class: str | None = None,
        year: int | None = None,
    ) -> dict[str, Any]:
        resolved = await self.resolve_village_norm(village, fuzzy=True)
        filters = {
            "land_class": land_class,
            "transaction_class": transaction_class,
            "year": year,
        }
        if resolved is None:
            return {
                "resolved_village": None,
                "filters": filters,
                "rates": [],
                "note": "village not found",
            }
        where = [
            "village_norm = %(v)s",
            "market_value > 0",
            "extent_val > 0",
            "extent_unit IS NOT NULL",
        ]
        params: dict[str, Any] = {"v": resolved}
        if year is not None:
            where.append("year = %(year)s")
            params["year"] = year
        if land_class:
            where.append("land_class = %(land_class)s")
            params["land_class"] = land_class.upper()
        if transaction_class:
            where.append("txn_class = %(transaction_class)s")
            params["transaction_class"] = transaction_class.upper()
        rate = "market_value::numeric / extent_val"
        rates = await self.db.fetch_all(
            f"SELECT extent_unit, count(*) AS n, round(avg({rate})) AS avg_rate, "
            f"round(percentile_cont(0.5) WITHIN GROUP (ORDER BY {rate})) AS median_rate, "
            f"round(min({rate})) AS min_rate, round(max({rate})) AS max_rate "
            f"FROM {self.settings.records_fqn} WHERE {' AND '.join(where)} "
            "GROUP BY extent_unit ORDER BY n DESC",
            params,
        )
        return {
            "resolved_village": resolved,
            "filters": filters,
            "rate_unit": "rupees per <extent_unit>",
            "rates": rates,
        }

    async def search_semantic_boundaries(
        self,
        query_text: str,
        village: str | None = None,
        limit: int = 5,
        ef_search: int = 60,
    ) -> list[dict[str, Any]]:
        if not query_text.strip():
            raise ToolInputError("query_text is required.")
        resolved: str | None = None
        if village:
            resolved = await self.resolve_village_norm(village, fuzzy=True)
            if resolved is None:
                return []
        vector = to_vector_literal(await embed_query(query_text, self.settings))
        result_limit = max(1, min(int(limit), 50))
        fetch_limit = result_limit * 12 if resolved else result_limit
        params: dict[str, Any] = {
            "query_vector": vector,
            "fetch_limit": fetch_limit,
            "limit": result_limit,
        }
        sql = (
            "WITH hits AS ("
            " SELECT rid, s_no, embedding <=> "
            f"CAST(%(query_vector)s AS halfvec({self.settings.embed_dimensions})) AS dist "
            f"FROM {self.settings.boundary_vectors_fqn} "
            "ORDER BY embedding <=> "
            f"CAST(%(query_vector)s AS halfvec({self.settings.embed_dimensions})) "
            "LIMIT %(fetch_limit)s"
            ") SELECT r.rid, r.s_no, r.village, r.survey_no, "
            "(1 - h.dist) AS score, r.boundary_north, r.boundary_south, "
            "r.boundary_east, r.boundary_west FROM hits h "
            f"JOIN {self.settings.records_fqn} r USING (rid, s_no) "
        )
        if resolved:
            sql += "WHERE r.village_norm = %(village)s "
            params["village"] = resolved
        sql += "ORDER BY h.dist LIMIT %(limit)s"
        return await self.db.fetch_all(
            sql,
            params,
            local_settings={"hnsw.ef_search": max(1, min(int(ef_search), 1000))},
        )

    async def generate_report(
        self,
        village: str | None = None,
        area_sro: str | None = None,
        transaction_class: str | None = None,
        land_class: str | None = None,
        year: int | None = None,
        party: str | None = None,
        rid: str | None = None,
        s_no: int | None = None,
        title: str | None = None,
    ) -> str:
        if party:
            return await self._party_report(party, title)
        if rid:
            return await self._dossier_report(rid, s_no, title)
        return await self._market_report(
            village, area_sro, transaction_class, land_class, year, title
        )

    async def _party_report(self, name: str, title: str | None) -> str:
        now = datetime.now(timezone.utc)
        scope = f"Party: {name}"
        report_id = _report_id(now, scope)
        heading = title or "PATTADAR PARTY PORTFOLIO REPORT"
        query = _normalize_name(name)
        if not query:
            return "\n".join(
                _header(heading, report_id, now, scope)
                + ["_Empty or invalid name._"]
                + _footer(report_id, now)
            )
        cap = 1000
        rows = await self.db.fetch_all(
            "SELECT p.name AS matched_name, p.role, p.side, "
            "similarity(p.name_norm, %(query)s) AS score, r.rid, r.s_no, r.village, "
            "r.survey_no, r.txn_class, r.transaction_type, r.market_value, "
            "r.extent_val, r.extent_unit, r.reg_date "
            f"FROM {self.settings.party_fqn} p "
            f"JOIN {self.settings.records_fqn} r USING (rid, s_no) "
            "WHERE p.name_norm %% %(query)s ORDER BY r.reg_date DESC NULLS LAST "
            "LIMIT %(cap)s",
            {"query": query, "cap": cap},
            local_settings={"pg_trgm.similarity_threshold": 0.35},
        )
        lines = _header(heading, report_id, now, scope)
        if not rows:
            return "\n".join(
                lines + [f'_No parties matched "{name}"._'] + _footer(report_id, now)
            )
        documents = {row["rid"] for row in rows}
        villages = {row["village"] for row in rows if row["village"]}
        dates = [str(row["reg_date"]) for row in rows if row["reg_date"]]
        best = max(rows, key=lambda row: row["score"] or 0)["matched_name"]

        def side_aggregate(side: str) -> tuple[int, float]:
            matching = [row for row in rows if row["side"] == side]
            return len(matching), sum((row["market_value"] or 0) for row in matching)

        seller_count, seller_value = side_aggregate("executant")
        buyer_count, buyer_value = side_aggregate("claimant")
        other_count = sum(
            1 for row in rows if row["side"] not in ("executant", "claimant")
        )
        lines.extend(
            [
                "## 1. Summary",
                _table(
                    ["Metric", "Value"],
                    [
                        ["Closest matched name", best],
                        ["Deed rows", _num(len(rows)) + (" (capped)" if len(rows) >= cap else "")],
                        ["Distinct documents", _num(len(documents))],
                        ["Villages spanned", _num(len(villages))],
                        ["Date range", f"{min(dates)} → {max(dates)}" if dates else "—"],
                        ["As seller-side (executant)", f"{_num(seller_count)} deeds · {_inr(seller_value)}"],
                        ["As buyer-side (claimant)", f"{_num(buyer_count)} deeds · {_inr(buyer_value)}"],
                        ["Other roles", _num(other_count)],
                    ],
                ),
                "## 2. Deeds (most recent first)",
                _table(
                    ["Date", "Village", "Survey", "Role/Side", "Txn", "Market value"],
                    [
                        [
                            row["reg_date"] or "—",
                            row["village"] or "—",
                            row["survey_no"] or "—",
                            f'{row["role"] or "?"}/{row["side"] or "?"}',
                            row["txn_class"] or row["transaction_type"] or "—",
                            _inr(row["market_value"]),
                        ]
                        for row in rows[:30]
                    ],
                ),
            ]
        )
        if len(rows) > 30:
            lines.append(f"_…showing 30 of {len(rows)} deeds._\n")
        return "\n".join(lines + _footer(report_id, now))

    async def _dossier_report(
        self, rid: str, s_no: int | None, title: str | None
    ) -> str:
        now = datetime.now(timezone.utc)
        scope = f"Document: {rid}" + (f" · s_no {s_no}" if s_no is not None else "")
        report_id = _report_id(now, scope)
        heading = title or "PATTADAR PROPERTY DOSSIER"
        where = "rid = %(rid)s"
        params: dict[str, Any] = {"rid": rid}
        if s_no is not None:
            where += " AND s_no = %(s_no)s"
            params["s_no"] = s_no
        params["dossier_limit"] = 201
        records = await self.db.fetch_all(
            "SELECT rid, s_no, doc_no, year, sro_name, book_no, page_no, village, "
            "survey_no, plot_no, house_no, apartment_name, extent_val, extent_unit, "
            "property_type, land_class, transaction_type, txn_class, market_value, "
            "consideration_value, reg_date, exec_date, pres_date, sellers, buyers, "
            "other_parties, boundary_north, boundary_south, boundary_east, boundary_west "
            f"FROM {self.settings.records_fqn} WHERE {where} ORDER BY s_no "
            "LIMIT %(dossier_limit)s",
            params,
        )
        if len(records) > 200:
            raise ToolInputError(
                "This document has more than 200 property rows; provide s_no for an exact dossier."
            )
        lines = _header(heading, report_id, now, scope)
        if not records:
            return "\n".join(
                lines + [f"_No record found for rid {rid}._"] + _footer(report_id, now)
            )
        first = records[0]
        lines.extend(
            [
                "## Document",
                _table(
                    ["Field", "Value"],
                    [
                        ["RID", rid],
                        ["Doc no", first["doc_no"] or "—"],
                        ["Year", first["year"] or "—"],
                        ["SRO", first["sro_name"] or "—"],
                        ["Book / Page", f'{first["book_no"] or "—"} / {first["page_no"] or "—"}'],
                        ["Properties in document", _num(len(records))],
                    ],
                ),
            ]
        )
        for record in records:
            extent = (
                f'{record["extent_val"]} {record["extent_unit"] or ""}'.strip()
                if record["extent_val"] is not None
                else "—"
            )
            lines.extend(
                [
                    f"## Property — s_no {record['s_no']}",
                    _table(
                        ["Field", "Value"],
                        [
                            ["Village", record["village"] or "—"],
                            ["Survey / Plot / House", f'{record["survey_no"] or "—"} / {record["plot_no"] or "—"} / {record["house_no"] or "—"}'],
                            ["Apartment", record["apartment_name"] or "—"],
                            ["Extent", extent],
                            ["Land class / Type", f'{record["land_class"] or "—"} / {record["property_type"] or "—"}'],
                            ["Transaction", f'{record["txn_class"] or "—"} ({record["transaction_type"] or "—"})'],
                            ["Market value", _inr(record["market_value"])],
                            ["Consideration", _inr(record["consideration_value"])],
                            ["Reg / Exec / Pres date", f'{record["reg_date"] or "—"} / {record["exec_date"] or "—"} / {record["pres_date"] or "—"}'],
                        ],
                    ),
                    "**Parties**",
                    _table(
                        ["Side", "Names"],
                        [
                            ["Sellers", ", ".join(record["sellers"]) if record["sellers"] else "—"],
                            ["Buyers", ", ".join(record["buyers"]) if record["buyers"] else "—"],
                            ["Other", ", ".join(record["other_parties"]) if record["other_parties"] else "—"],
                        ],
                    ),
                    "**Boundaries**",
                    _table(
                        ["Direction", "Abutment"],
                        [
                            ["North", record["boundary_north"] or "—"],
                            ["South", record["boundary_south"] or "—"],
                            ["East", record["boundary_east"] or "—"],
                            ["West", record["boundary_west"] or "—"],
                        ],
                    ),
                ]
            )
        return "\n".join(lines + _footer(report_id, now))

    async def _market_report(
        self,
        village: str | None,
        area_sro: str | None,
        transaction_class: str | None,
        land_class: str | None,
        year: int | None,
        title: str | None,
    ) -> str:
        where: list[str] = []
        params: dict[str, Any] = {}
        scope_parts: list[str] = []
        if village:
            resolved = await self.resolve_village_norm(village, fuzzy=True)
            where.append("village_norm = %(village)s")
            params["village"] = resolved or "__no_match__"
            scope_parts.append(f"Village: {resolved or village + ' (no match)'}")
        if area_sro:
            where.append("sro_name ILIKE %(sro)s")
            params["sro"] = f"%{area_sro}%"
            scope_parts.append(f"Area/SRO: {area_sro}")
        if transaction_class:
            where.append("txn_class = %(transaction_class)s")
            params["transaction_class"] = transaction_class.upper()
            scope_parts.append(f"Txn class: {transaction_class}")
        if land_class:
            where.append("land_class = %(land_class)s")
            params["land_class"] = land_class.upper()
            scope_parts.append(f"Land class: {land_class}")
        if year:
            where.append("year = %(year)s")
            params["year"] = int(year)
            scope_parts.append(f"Year: {year}")
        where_sql = "WHERE " + " AND ".join(where) if where else ""
        conjunction = "AND" if where_sql else "WHERE"
        scope = " · ".join(scope_parts) if scope_parts else "Entire corpus (all districts, all years)"
        table = self.settings.records_fqn

        overview = (
            await self.db.fetch_all(
                "SELECT count(*) AS records, count(DISTINCT rid) AS documents, "
                "count(DISTINCT village_norm) AS villages, min(reg_date) AS first_date, "
                "max(reg_date) AS last_date, "
                "count(*) FILTER (WHERE market_value > 0) AS valued, "
                "sum(market_value) AS total_mv, "
                "round(avg(market_value) FILTER (WHERE market_value > 0)) AS avg_mv, "
                "percentile_cont(0.5) WITHIN GROUP (ORDER BY market_value) "
                "FILTER (WHERE market_value > 0) AS median_mv, "
                f"sum(consideration_value) AS total_cons FROM {table} {where_sql}",
                params,
            )
        )[0]
        by_transaction = await self.db.fetch_all(
            "SELECT COALESCE(txn_class,'(unclassified)') AS k, count(*) AS n, "
            f"sum(market_value) AS mv FROM {table} {where_sql} "
            "GROUP BY 1 ORDER BY n DESC LIMIT 12",
            params,
        )
        by_land = await self.db.fetch_all(
            "SELECT COALESCE(land_class,'(unclassified)') AS k, count(*) AS n "
            f"FROM {table} {where_sql} GROUP BY 1 ORDER BY n DESC LIMIT 10",
            params,
        )
        by_extent = await self.db.fetch_all(
            "SELECT COALESCE(extent_unit,'(none)') AS k, count(*) AS n, "
            f"round(sum(extent_val)::numeric,2) AS total FROM {table} {where_sql} "
            f"{conjunction} extent_val IS NOT NULL GROUP BY 1 ORDER BY n DESC",
            params,
        )
        top_villages = [] if village else await self.db.fetch_all(
            "SELECT village, count(*) AS n, sum(market_value) AS mv "
            f"FROM {table} {where_sql} {conjunction} village IS NOT NULL "
            "GROUP BY village ORDER BY n DESC LIMIT 10",
            params,
        )
        by_year = [] if year else await self.db.fetch_all(
            f"SELECT year, count(*) AS n FROM {table} {where_sql} "
            f"{conjunction} year IS NOT NULL GROUP BY year ORDER BY year DESC LIMIT 12",
            params,
        )

        now = datetime.now(timezone.utc)
        report_id = _report_id(now, scope)
        coverage = f"{overview['first_date'] or '—'} → {overview['last_date'] or '—'}"
        lines = _header(title or "PATTADAR LAND RECORD REPORT", report_id, now, scope, coverage)
        lines.extend(
            [
                "## 1. Summary",
                _table(
                    ["Metric", "Value"],
                    [
                        ["Records", _num(overview["records"])],
                        ["Distinct documents (rid)", _num(overview["documents"])],
                        ["Villages covered", _num(overview["villages"])],
                        ["Records with a market value", _num(overview["valued"])],
                        ["Total market value", _inr(overview["total_mv"])],
                        ["Median market value", _inr(overview["median_mv"])],
                        ["Average market value", _inr(overview["avg_mv"])],
                        ["Total consideration value", _inr(overview["total_cons"])],
                    ],
                ),
                "## 2. Transactions by class",
                _table(
                    ["Transaction class", "Records", "Total market value"],
                    [[row["k"], _num(row["n"]), _inr(row["mv"])] for row in by_transaction],
                ),
                "## 3. Land classification",
                _table(["Land class", "Records"], [[row["k"], _num(row["n"])] for row in by_land]),
                "## 4. Extent (by unit — not summed across types)",
                _table(
                    ["Unit", "Records", "Total extent"],
                    [
                        [row["k"], _num(row["n"]), f'{row["total"]:,}' if row["total"] is not None else "—"]
                        for row in by_extent
                    ],
                ),
            ]
        )
        if top_villages:
            lines.extend(
                [
                    "## 5. Top villages by activity",
                    _table(
                        ["Village", "Records", "Total market value"],
                        [[row["village"], _num(row["n"]), _inr(row["mv"])] for row in top_villages],
                    ),
                ]
            )
        if by_year:
            lines.extend(
                [
                    "## 6. Activity by year (most recent)",
                    _table(["Year", "Records"], [[row["year"], _num(row["n"])] for row in by_year]),
                ]
            )
        return "\n".join(lines + _footer(report_id, now))
